file(MAKE_DIRECTORY "${OUTPUT_DIR}")
set(header "#pragma once\n#include <cstddef>\nnamespace embedded_themes {\nextern const char* const json[5];\nextern const unsigned char background[];\nextern const std::size_t background_size;\n}\n")
set(source "#include \"embedded_themes.h\"\nnamespace embedded_themes {\nconst char* const json[5] = {\n")
foreach(name dark indigo vermillion classic_steam crimson)
    file(READ "${THEMES_DIR}/theme_${name}.json" content)
    string(APPEND source "R\"theme_json(${content})theme_json\",\n")
endforeach()
string(APPEND source "};\nconst unsigned char background[] = {\n")
file(READ "${THEMES_DIR}/bg_crimson.png" data HEX)
string(REGEX REPLACE "([0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f])" "\\1\n" data "${data}")
string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," data "${data}")
string(APPEND source "${data}\n};\nconst std::size_t background_size = sizeof(background);\n}\n")
file(WRITE "${OUTPUT_DIR}/embedded_themes.h" "${header}")
file(WRITE "${OUTPUT_DIR}/embedded_themes.cpp" "${source}")
